[EDU-5142] fix: adjust WAF custom rules note
aziontech/docs pull request #1164
Opened 2024-08-16 18:02 UTC by MarianaAguilera

### Related issue: 

[EDU-5142]

### Changes

- Adjust WAF custom rules note.

### Additional links

n/a.

2024-08-16 18:05 UTC, GabrielAzion approved these changes

2024-08-16 18:05 UTC, gabriel-azion approved these changes

2024-08-16 19:18 UTC, arturdj requested changes
Tem um erro ainda na frase.

2024-08-16 19:18 UTC, arturdj commented on src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
> -Requests that fall under rules 1 to 18 might be blocked in some cases, even if the WAF is operating in *learning* mode. Read the [Rules Engine for Edge Firewall](/en/documentation/products/secure/edg
Na frase, a única regra em que isso se aplica, agora, é a 13.

> "Requests that fall under rule **13** will be blocked in some cases (...)"

2024-08-16 19:19 UTC, MarianaAguilera commented on src/content/docs/en/pages/main-menu/reference/secure/edge-firewall/web-application-firewall/custom-allowed-rule.mdx
> +Requests that fall under rules 1 to 18 will be blocked in some cases, even if the WAF is operating in *learning* mode. Read the [Rules Engine for Edge Firewall](/en/documentation/products/secure/edge
```suggestion
Requests that fall under rule 13 will be blocked in some cases, even if the WAF is operating in *learning* mode. Read the [Rules Engine for Edge Firewall](/en/documentation/products/secure/edge-firewall/rules-engine/) documentation for the definition of learning/blocking modes. Read this guide [how to check your WAF mode](/en/documentation/products/guides/how-to-check-your-waf-mode/).
```

2024-08-16 19:19 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/menu-principal/referencia/secure/edge-firewall/web-application-firewall/waf-custom-allowed-rules.mdx
> +Requisições que se enquadram nas regras de 1 a 18 serão bloqueadas em alguns casos, mesmo que o WAF esteja operando em modo *learning*. Veja na documentação do [Rules Engine para Edge Firewall](/pt-b
```suggestion
Requisições que se enquadram na regra 13 serão bloqueadas em alguns casos, mesmo que o WAF esteja operando em modo *learning*. Veja na documentação do [Rules Engine para Edge Firewall](/pt-br/documentacao/produtos/secure/edge-firewall/rules-engine/) a definição dos modos learning/blocking. Veja no guia [como verificar o modo do seu WAF](/pt-br/documentacao/produtos/guias/como-verificar-modo-do-seu-waf/).
```

2024-08-20 18:44 UTC, arturdj approved these changes

2024-08-20 18:45 UTC, merged