EDU 2232-team-permissions-reference
aziontech/docs pull request #121
Opened 2023-08-18 04:52 UTC by mariiaguirre

Atualização conforme template + descrição das permissions

2023-08-18 12:33 UTC, bru-andrade reviewed
Você vai ver altas mudanças na tabela hehe. 🤠

2023-08-18 12:42 UTC, gabriel-azion requested changes
Some typos and other things... Would you slack me when you apply the corrections?

2023-08-18 14:25 UTC, hannah-sk requested changes
typos e estilo

2023-08-18 18:34 UTC, hannah-sk approved these changes

2023-08-21 19:58 UTC, gabriel-azion approved these changes

2023-08-21 20:03 UTC, merged