[EDU-5669] feature: add and publish Terms and Conditions of the Savings Plan
aziontech/docs pull request #1382
Opened 2024-11-27 20:30 UTC by MarianaAguilera

### Related issue: 

[EDU-5669]

### Changes

Add and publish the Terms and Conditions of the Savings Plan files EN/PT.
Include the link in the Agreements page EN/PT.

### Additional links

n/a.

2024-11-27 21:28 UTC, isidrohernandezazion approved these changes

2024-11-28 11:58 UTC, guiafonso-ol approved these changes

2024-12-06 13:09 UTC, MarianaAguilera commented on src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
> +4.1 The following are added to the Terms and Definitions of the Customer Agreement:
A numer

2024-12-06 13:10 UTC, MarianaAguilera commented on src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
> +4.1 The following are added to the Terms and Definitions of the Customer Agreement:
```suggestion
4.1. The following are added to the Terms and Definitions of the Customer Agreement:
```

2024-12-06 13:11 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/contratos/savings-plan/savings-plan.mdx
> +4.1 Acrescentam-se aos Termos e Definições do Contrato de Cliente:
```suggestion
4.1. Acrescentam-se aos Termos e Definições do Contrato de Cliente:
```

2024-12-06 14:02 UTC, mrmessa requested changes
@MarianaAguilera, attached to the issue on Jira, we had a review of the legal to English text.

2024-12-12 14:06 UTC, mrmessa requested changes

2024-12-12 14:08 UTC, MarianaAguilera commented on src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
> +Savings Plan is one of the ways of contracting Azion Products and Services, subject to the terms of the [Customer Agreement](https://www.azion.com/en/documentation/agreements/customer-agreement/) and
```suggestion
Savings Plan is one of the ways of contracting Azion Products and Services, subject to the terms of the [Customer Agreement](/en/documentation/agreements/customer-agreement/) and other related documents. In this format, the Customer commits to pay a financial amount during the Effective Term (the "Purchase Commitment") and can enjoy discounts on On Demand Prices published on the subscription date, in accordance with their Service Order ("On Demand Price Discount"), except on third-party products listed on the Azion Marketplace.
```

2024-12-17 17:41 UTC, MarianaAguilera commented on src/content/docs/en/pages/agreements/2021-01-14-index.mdx
> +- [Terms and Conditions of the Savings Plan](/en/documentation/agreements/terms-and-conditions-savings-plan/)
```suggestion
- [Savings Plan Terms and Conditions](/en/documentation/agreements/savings-plan-terms-and-conditions/)
```

2024-12-17 18:09 UTC, MarianaAguilera commented on src/content/docs/en/pages/agreements/savings-plan/savings-plan.mdx
> +description: Terms and Conditions of the Savings Plan
```suggestion
description: Terms and Conditions related to the Savings Plan
```

2024-12-17 18:20 UTC, mrmessa approved these changes

2024-12-18 11:13 UTC, merged