azion-cli-v1
aziontech/docs pull request #188
Opened 2023-09-04 16:58 UTC by gabriel-azion

**Important** 

- English is already reviewed, if you want to review, no probs, reviews are welcome...

- Portuguese is not reviewed yet.

- There are some menu and cards changes. 

---

Add new cli docs.

I'll use this PR for grammar and style review, but further I'll use the same branch for other adjustments (menu. cards).

---

Revisão geral liberada, após aprovação, subirei para prod.

2023-09-04 17:19 UTC, hannah-sk requested changes
style + questions regarding titles

2023-09-04 17:53 UTC, ghost approved these changes

2023-09-06 17:04 UTC, hannah-sk approved these changes

2023-09-11 16:19 UTC, bru-andrade approved these changes

2023-09-21 17:28 UTC, robsongajunior approved these changes

2023-09-21 19:30 UTC, merged