[EDU-2136] Add watermark parameters and example
aziontech/docs pull request #301
Opened 2023-10-03 13:22 UTC by bru-andrade

### Related issue: [EDU-2136]

### Changes

- Added new supported parameters
- Added example with Azion logo

### Additional links

2023-10-03 14:12 UTC, hannah-sk commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +Add watermarks to your images by appending the query `?ims=filters:watermark(WatermarkURL,X,Y,Alpha,WidthRatio,HeightRatio)`, where:
```suggestion
You can add watermarks to your images by appending the query `?ims=filters:watermark(WatermarkURL,X,Y,Alpha,WidthRatio,HeightRatio)`, where:
```

2023-10-03 14:13 UTC, hannah-sk commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +  - Enter a positive or negative number followed by a 'p' (for example, `20p`) to calculate the horizontal position as a percentage of the image width.
```suggestion
  - Enter a positive or negative number followed by a `p` (for example, `20p`) to calculate the horizontal position as a percentage of the image width.
```

2023-10-03 14:19 UTC, hannah-sk commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +- `HeightRatio` is an optional parameter that sets the watermark height as a percentage relative to the image. If you don't specify a value, it will default to `none`.
```suggestion
- `WidthRatio` is an optional parameter that sets the watermark width as a percentage relative to the image. If you don't specify a value, it'll default to `none`.
- `HeightRatio` is an optional parameter that sets the watermark height as a percentage relative to the image. If you don't specify a value, it'll default to `none`.
```

2023-10-03 14:24 UTC, hannah-sk commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +Adicione marcas d'água às suas imagens acrescentando a query `?ims=filters:watermark(WatermarkURL,X,Y,Alpha,WidthRatio,HeightRatio)`, onde:
```suggestion
Você pode adicionar marcas d'água às suas imagens acrescentando a query `?ims=filters:watermark(WatermarkURL,X,Y,Alpha,WidthRatio,HeightRatio)`, onde:
```

2023-10-03 14:25 UTC, MarianaAguilera approved these changes

2023-10-03 14:25 UTC, MarianaAguilera commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +- `WidthRatio` is an optional parameter that sets the watermark width as a percentage relative to the image. If you don't specify a value, it will default to `none`.
```suggestion
- `WidthRatio` is an optional parameter that sets the watermark width as a percentage relative to the image. If you don't specify a value, it'll default to `none`.
```

2023-10-03 14:25 UTC, MarianaAguilera commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +- `HeightRatio` is an optional parameter that sets the watermark height as a percentage relative to the image. If you don't specify a value, it will default to `none`.
```suggestion
- `HeightRatio` is an optional parameter that sets the watermark height as a percentage relative to the image. If you don't specify a value, it'll default to `none`.
```

2023-10-03 14:25 UTC, hannah-sk commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +  - Insira o valor `repeat`, para preencher a imagem com repetições horizontais da marca d'água.
```suggestion
  - Insira o valor `center`,para centralizar a marca d'água horizontalmente.
  - Insira o valor `repeat` para preencher a imagem com repetições horizontais da marca d'água.
```

2023-10-03 14:25 UTC, hannah-sk commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +  - Insira um número positivo ou negativo seguido de um 'p' (por exemplo, `20p`) para calcular a posição horizontal como uma porcentagem da largura da imagem.
```suggestion
  - Insira um número positivo ou negativo seguido de um `p` (por exemplo, `20p`) para calcular a posição horizontal como uma porcentagem da largura da imagem.
```

2023-10-03 14:25 UTC, hannah-sk commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +  - Insira o valor `repeat`, para preencher a imagem com repetições verticais da marca d'água.
```suggestion
  - Insira o valor `center` para centralizar a marca d'água verticalmente.
  - Insira o valor `repeat` para preencher a imagem com repetições verticais da marca d'água.
```

2023-10-03 14:25 UTC, hannah-sk commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +  - Insira um número positivo ou negativo seguido por um 'p' (por exemplo, `20p`) para calcular a posição vertical como uma porcentagem da largura da imagem.
```suggestion
  - Insira um número positivo ou negativo seguido por um `p` (por exemplo, `20p`) para calcular a posição vertical como uma porcentagem da largura da imagem.
```

2023-10-03 14:26 UTC, hannah-sk requested changes
some suggestions + style corrections

2023-10-03 19:10 UTC, bru-andrade commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +  - Enter the value `repeat`, to fill the image with vertical repetitions of the watermark.
```suggestion
  - Enter the value `center` to center the watermark vertically. 
  - Enter the value `repeat` to fill the image with vertical repetitions of the watermark.
```

2023-10-03 19:11 UTC, bru-andrade commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +  - Enter the value `repeat`, to fill the image with horizontal repetitions of the watermark.
```suggestion
  - Enter the value `center`, to center the watermark horizontally. 
  - Enter the value `repeat` to fill the image with horizontal repetitions of the watermark.
```

2023-10-04 14:21 UTC, bru-andrade commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +Add watermarks to your images by appending the query `?ims=filters:watermark(WatermarkURL,X,Y,Alpha,WidthRatio,HeightRatio)`, where:
Estou deixando como padrão o imperativo mesmo, como no style guide que a Mari

2023-10-05 14:25 UTC, peeetry commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +<p align="center">[![Image_Processor_1](/assets/docs/images/image-processor/Image_Processor_2.png?ims=filters:watermark(https://raw.githubusercontent.com/aziontech/docs/main/public/assets/docs/images
hmm

2023-10-05 14:25 UTC, peeetry commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +<p align="center">[![Image_Processor_1](/assets/docs/images/image-processor/Image_Processor_2.png?ims=filters:watermark(https://raw.githubusercontent.com/aziontech/docs/main/public/assets/docs/images
hmm

2023-10-06 12:23 UTC, hannah-sk commented on src/content/docs/en/pages/products/edge-application/image-processor.mdx
> +  - Enter the value `repeat`, to fill the image with horizontal repetitions of the watermark.
```suggestion
  - Enter the value `repeat` to fill the image with horizontal repetitions of the watermark.
```

2023-10-06 12:23 UTC, hannah-sk approved these changes

2023-10-06 15:03 UTC, bru-andrade commented on src/content/docs/pt-br/pages/produtos/edge-application/image-processor/index.mdx
> +<p align="center">[![Image_Processor_1](/assets/docs/images/image-processor/Image_Processor_2.png?ims=filters:watermark(https://raw.githubusercontent.com/aziontech/docs/main/public/assets/docs/images
https://www.azion.com/assets/docs/images/image-processor/Image_Processor_2.png?ims=filters:watermark(https://raw.githubusercontent.com/aziontech/docs/main/public/assets/docs/images/azion-logo.png,repeat,20p,50,10,none)

2023-10-06 17:12 UTC, merged