EDU-2367-EN-API-Overview-for-docs-portal
aziontech/docs pull request #311
Opened 2023-10-06 20:39 UTC by peeetry

Related issue: [EDU-2367](https://aziontech.atlassian.net/browse/EDU-2367)

Changes:

* Introduction of API Overview.

2023-10-09 12:21 UTC, hannah-sk commented on src/content/docs/en/pages/azion-api/overview/azion-api-overview.mdx
> +description: Learn more about oficial endpoints, methods, and API use cases of the Azion RESTful API.
```suggestion
description: Learn more about official endpoints, methods, and API use cases of the Azion RESTful API.
```

2023-10-09 12:22 UTC, hannah-sk commented on src/content/docs/en/pages/azion-api/overview/azion-api-overview.mdx
> +Azion API documentation offers code examples to make requests with the terminal, using the curl tool, or to automate them with programming languages.
```suggestion
Azion API documentation offers code examples to make requests with the terminal, using the curl command, or to automate them with programming languages. 
```

2023-10-09 12:26 UTC, hannah-sk commented on src/content/docs/en/pages/azion-api/overview/azion-api-overview.mdx
> +The **Azion API** is a *RESTful API* based on *HTTPS* requests, that allows users to fully interact with Azion products through API requests. Most API endpoints have the main HTTP methods (`GET`, `PO
```suggestion
The **Azion API** is a *RESTful API* based on *HTTPS* requests, that allows users to fully interact with Azion products through API requests. The complete Azion API collection is on Postman

<Button href="https://api.azion.com/" text="go to Azion API collection"></Button>

Most API endpoints have the main HTTP methods (`GET`, `POST`, `PUT`, `PATCH`, and `DELETE`), so you can create, read, update, and delete Azion configuration instances. All changes made through the API are reflected on the [Real-Time Manager (RTM)](https://manager.azion.com).
```

2023-10-09 12:26 UTC, hannah-sk commented on src/content/docs/en/pages/azion-api/overview/azion-api-overview.mdx
> +
```suggestion

import Button from '~/components/Button.astro'

```

2023-10-09 12:27 UTC, hannah-sk commented on src/content/docs/en/pages/azion-api/overview/azion-api-overview.mdx
> +The **Azion API** is a *RESTful API* based on *HTTPS* requests, that allows users to fully interact with Azion products through API requests. Most API endpoints have the main HTTP methods (`GET`, `PO
there's a link to the intro right after, but it seemed importante to clarify it's on Postman and add the button. we're using it in most docs!

2023-10-09 12:28 UTC, hannah-sk requested changes
one typo correction and a few suggestions!

2023-10-09 13:00 UTC, MarianaAguilera approved these changes
Approved with Hannah suggestions.

2023-10-17 16:58 UTC, peeetry commented on src/content/docs/en/pages/azion-api/overview/azion-api-overview.mdx
> +## Make API resquests
```suggestion
## Make API requests
```

2023-10-18 12:14 UTC, peeetry commented
Closed to be reopened with the right GitHub files structure.

2023-10-18 12:14 UTC, closed without merging