EDU-2367-PT-Create-API-overview
aziontech/docs pull request #352
Opened 2023-10-17 19:44 UTC by peeetry

Tarefa relacionada: [EDU-2367](https://aziontech.atlassian.net/browse/EDU-2367)

Alterações:

* Introdução da documentação `Primeiros passos com a API da Azion`.

2023-10-17 20:25 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +- Uma conta no **Real-Time Manager (RTM)**.
```suggestion
- [Uma conta no Real-Time Manager (RTM)](/pt-br/documentacao/produtos/contas/criar-uma-conta/).
```

2023-10-17 20:26 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +- Um **personal token**.
```suggestion
- [Um personal token](/pt-br/documentacao/produtos/gestao-de-contas/personal-tokens/).
```

2023-10-17 20:27 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +A documentação da API da Azion oferece exemplos de como fazer requisições utilizando o terminal, o comando curl, ou como automatizar essas requisições, implementando seus snippets em softwares.
```suggestion
A documentação da API da Azion oferece exemplos de como fazer requisições utilizando o terminal, o comando cURL, ou como automatizar essas requisições, implementando seus snippets em softwares.
```

2023-10-17 20:27 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Para trocar a linguagem do exemplo, navegue até `Example Request` e mude de curl para outra linguagem de programação desejada.
```suggestion
Para trocar a linguagem do exemplo, navegue até `Example Request` e mude de cURL para outra linguagem de programação desejada.
```

2023-10-17 21:46 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Esta documentação irá guiá-lo nos primeiros passos de utilização da **Azion API**.
lhe guiar? para evitar o masculino.

2023-10-17 21:47 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite usuários interagir com os produtos da Azion. A coleção completa dos métodos e endpoints da API está disponí
```suggestion
A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite a usuários interagir com os produtos da Azion. A coleção completa dos métodos e endpoints da API está disponível na documentação oficial.
```

2023-10-17 21:47 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Esta documentação irá guiá-lo nos primeiros passos de utilização da **Azion API**.
API da Azion ou Azion API?

2023-10-17 21:47 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +:::dica
```suggestion
:::tip[dica]
```

2023-10-17 21:48 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Para fazer requisições com a **API da Azion** você precisa:
```suggestion
Para fazer requisições com a **API da Azion**, você precisa de:
```

2023-10-17 21:49 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +:::dica
```suggestion
:::tip[dica]
```

2023-10-17 21:49 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Veja [como criar uma conta no RTM](/pt-br/documentacao/produtos/contas/criar-uma-conta/) e como gerar um [personal token](/pt-br/documentacao/produtos/gestao-de-contas/personal-tokens/) para usar com
aceitando as sugestões da @bru-andrade, não precisaria dessa tip.

2023-10-17 21:50 UTC, hannah-sk requested changes
poucas correções e duas perguntas!

2023-10-17 22:39 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Esta documentação irá guiá-lo nos primeiros passos de utilização da **Azion API**.
```suggestion
Esta documentação vai lhe guiar nos primeiros passos de utilização da **Azion da API**.
```

2023-10-17 22:39 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +<Button href="https://api.azion.com/" text="Ir para documentação da API Azion"></Button>
```suggestion
<Button href="https://api.azion.com/" text="Ir para documentação da API da Azion"></Button>
```

2023-10-17 22:39 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +A maioria dos endpoints da API da Azion possuem os principais métodos HTTP (`GET`, `POST`, `PUT`, `PATCH` e `DELETE`), para que o usuário possa criar, ler, atualizar e excluir instâncias de configura
```suggestion
A maioria dos endpoints da API da Azion possuem os principais métodos HTTP (`GET`, `POST`, `PUT`, `PATCH` e `DELETE`) para que o usuário possa criar, ler, atualizar e excluir instâncias de configurações na Azion. Todas as alterações feitas por meio da API são refletidas no [Real-Time Manager (RTM)](https://manager.azion.com).
```

2023-10-18 11:58 UTC, peeetry commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Esta documentação irá guiá-lo nos primeiros passos de utilização da **Azion API**.
API da Azion!

2023-10-18 11:59 UTC, peeetry commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Esta documentação irá guiá-lo nos primeiros passos de utilização da **Azion API**.
```suggestion
Esta documentação conta com os primeiros passos para a utilização da **API da Azion**.
```

2023-10-18 12:07 UTC, peeetry commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +:::
```suggestion
```

2023-10-18 12:07 UTC, peeetry reviewed
Sugestões aceitas.

2023-10-18 12:11 UTC, MarianaAguilera approved these changes

2023-10-18 12:32 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite usuários interagirem com os produtos da Azion. A coleção completa dos métodos e endpoints da API está dispo
se permite algo (interagir) a alguém (a usuários).

precisa der "permite a usuários interagirem" ou "permite que usuários interajam"

2023-10-18 13:24 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite usuários interagirem com os produtos da Azion. A coleção completa dos métodos e endpoints da API está dispo
```suggestion
A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite a usuários interagirem com os produtos da Azion. A coleção completa dos métodos e endpoints da API está disponível na documentação oficial no Postman.
```

2023-10-18 13:24 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Para trocar a linguagem do exemplo da requisição, navegue até `Example Request` e mude de curl para outra linguagem de programação desejada.
em EN menciona o Postman em uma frase acima

2023-10-18 14:11 UTC, hannah-sk approved these changes

2023-10-20 12:07 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite que usuários interajam com os produtos da Azion. A coleção completa dos métodos e endpoints da API está dis
```suggestion
A **API da Azion** é uma *API RESTful* baseada em requisições *HTTP* e *HTTPS*, que permite que usuários interajam com os produtos da Azion. A coleção completa da API da Aziobn está disponível no Postman.
```

2023-10-20 12:08 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/recursos-adicionais/developer-tools/primeiros-passos-api.mdx
> +Para trocar a linguagem do exemplo da requisição, navegue até `Example Request` e mude de curl para outra linguagem de programação desejada.
```suggestion
Para trocar a linguagem do exemplo da requisição, navegue até `Example Request` e mude de curl para outra linguagem de programação desejada.

Você também pode clicar no botão **Run in Postman** para clonar a coleção e fazer requisições usando o próprio Postman.
```

2023-10-20 12:18 UTC, merged