[EDU-2722] Adjust Accounts content
aziontech/docs pull request #366
Opened 2023-10-20 14:22 UTC by bru-andrade

### Related issue: [EDU-2722]

### Changes

- Keep PT and EN consistent
- Added small descriptions to some pages

### Additional links

2023-10-20 15:09 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/manage-accounts/manage-account/teams-permissions.mdx
> +You must be the **Account Owner** or have the Edit Users permission to perform these settings.
```suggestion
You must be the **Account Owner** or have the **Edit Users** permission to perform these settings.
```

2023-10-20 15:11 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/personal-token.mdx
> +[Personal Tokens](/en/documentation/products/accounts/personal-tokens/) allow you to authenticate your access to interfaces and tools such as the [Azion CLI](/en/documentation/products/build/develop-
```suggestion
[Personal Tokens](/en/documentation/products/accounts/personal-tokens/) allow you to authenticate your access to interfaces and tools such as the [Azion CLI](/en/documentation/products/build/develop-with-azion/cli/) and [Azion API](/en/documentation/products/overview-azion-api/). 
```

2023-10-20 15:11 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/mfa.mdx
> +[Multi-Factor Authentication (MFA)](/documentation/products/accounts/multi-factor-authentication/) allows you to secure logins by requiring an extra layer to authentication.
traduzir para PT

2023-10-20 15:13 UTC, hannah-sk commented on src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/times-permissoes.mdx
> +Com [Teams Permissions](/en/documentation/products/accounts/teams-permissions/), você pode criar e gerenciar times, bem como controlar e configurar direitos de acesso para diferentes times em sua org
```suggestion
Com [Teams Permissions](/pt-br/documentacao/produtos/gestao-de-contas/teams-permissions/), você pode criar e gerenciar times, bem como controlar e configurar direitos de acesso para diferentes times em sua organização.
```

2023-10-20 15:14 UTC, hannah-sk requested changes
algumas correções, principalmente de um trecho que está em EN na página em PT

2023-10-20 20:03 UTC, MarianaAguilera commented on src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/delete-account.mdx
> +> The **Delete account** button only activates when the information mentioned above has been resolved.
Use a component?

2023-10-20 20:11 UTC, MarianaAguilera approved these changes
Approved with @hannah-sk's comments.

2023-10-23 13:24 UTC, bru-andrade commented on src/content/docs/en/pages/main-menu/manage-accounts/manage-profile/delete-account.mdx
> +> The **Delete account** button only activates when the information mentioned above has been resolved.
```suggestion
:::note
The **Delete account** button only activates when the information mentioned above has been resolved.
:::
```

2023-10-23 18:12 UTC, bru-andrade commented on src/content/docs/en/pages/main-menu/manage-accounts/manage-account/mfa.mdx
> +[Multi-Factor Authentication (MFA)](/documentation/products/accounts/multi-factor-authentication/) allows you to secure logins by requiring an extra layer to authentication.
```suggestion
[Multi-Factor Authentication (MFA)](/en/documentation/products/accounts/multi-factor-authentication/) allows you to secure logins by requiring an extra layer to authentication.
```

2023-10-23 18:13 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/activity-history.mdx
> +[Activity History](/en/documentation/products/accounts/activity-history/) permite que você acesse o histórico de todas as atividades da conta realizadas por qualquer usuário conectado à conta princip
```suggestion
[Activity History](/pt-br/documentacao/produtos/gestao-de-contas/activity-history/) permite que você acesse o histórico de todas as atividades da conta realizadas por qualquer usuário conectado à conta principal.
```

2023-10-23 18:16 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/sso.mdx
>  Para acessar o SSO Management:
```suggestion
Para acessar o **SSO Management**:
```

2023-10-23 18:16 UTC, bru-andrade commented on src/content/docs/en/pages/main-menu/manage-accounts/manage-account/sso.mdx
>  To access SSO Management:
```suggestion
To access **SSO Management**:
```

2023-10-23 18:31 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/mfa.mdx
> +[Multi-Factor Authentication (MFA)](/pt-br/documentacao/produtos/gestao-de-contas/multi-factor-authentication/) allows you to secure logins by requiring an extra layer to authentication.
```suggestion
[Multi-Factor Authentication (MFA)](/pt-br/documentacao/produtos/gestao-de-contas/multi-factor-authentication/) permite que você reforce a segurança de acessos à sua conta adicionando uma camada de autenticação.
```

2023-10-23 18:32 UTC, bru-andrade commented on src/content/docs/pt-br/pages/menu-principal/gerencie-contas/gerenciar-contas/sso.mdx
> +Se você tem um [plano Enterprise](https://www.azion.com/pt-br/precos/#planos) e tem SSO configurado para sua empresa, seus usuários podem logar no and have SSO configured for your company, your users
```suggestion
Se você tem um [plano Enterprise](https://www.azion.com/pt-br/precos/#planos) e tem SSO configurado para sua empresa, seus usuários podem logar no **Real-Time Manager (RTM)** usando suas credenciais de SSO.
```

2023-10-23 18:35 UTC, hannah-sk approved these changes

2023-10-23 18:39 UTC, merged