limits and quotas
aziontech/docs pull request #388
Opened 2023-10-30 18:32 UTC by hannah-sk

### Related issue: [EDU-2400]

### Changes

* Add new Limits and quotas doc v1.

2023-10-30 20:58 UTC, Leticia-JRosa requested changes

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Scope | Description | Limit |
```suggestion
| Scope | Description | Standard Limit |
```

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Scope | Description | Limit |
```suggestion
| Scope | Description | Standard Limit |
```

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Scope | Description | Limit |
Aqui a ideia de colocar o "Standard" é mostrar que esse é o limite básico, para reforçar que pode ser customizado.

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [L2 Caching](/en/documentation/products/edge-application/l2-caching/) | Content cahing | TTL equal or greater than 2592000 seconds (30 days) |
```suggestion
| [L2 Caching](/en/documentation/products/edge-application/l2-caching/) | Content caching | TTL equal or greater than 2592000 seconds (30 days) |
```

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Purge (History)](/en/documentation/products/edge-application/real-time-purge/) | Maximum number of wildcards URLs from which the Purge was requested. | Limited to 6 months and up to 1000
```suggestion
| [Real-Time Purge (History)](/en/documentation/products/edge-application/real-time-purge/) | Maximum number of wildcards URLs from which the Purge was requested | Limited to 6 months and up to 1000000 requests |
```

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +Quotas are defined by the Azion product being used and the service plan contracted. If a product, module, or feature doesn't have specified quotas, they run on a usage-based approach, meaning you pay
```suggestion
Quotas are defined by the Azion product being used and the service plan contracted. If a product, module or feature doesn't have specified quotas, they run on a usage-based approach, meaning you pay as you use them.
```

2023-10-30 20:58 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +[Edge Application](/en/documentation/products/edge-application/) product, modules, and features usage **quotas**, according to each service plan:
```suggestion
[Edge Application](/en/documentation/products/edge-application/) product, modules, and features usage **quotas** per account, according to each service plan:
```

2023-10-30 21:20 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Scope | Description | Limit |
```suggestion
| Scope | Description | Standard Limit |
```

2023-10-30 21:20 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Scope | Description | Limit |
```suggestion
| Scope | Description | Standard Limit |
```

2023-11-04 12:55 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +|  |  |
```suggestion
| DDoS Protection | DDoS Protection - 20 Gbps | Unmetered |
| DDoS Protection | DDoS Protection - 5 Gbps | Unmetered |
| DDoS Protection | DDoS Protection - 50 Gbps | Unmetered |
| DDoS Protection | DDoS Protection - Unlimited | Unmetered |
```

2023-11-04 13:01 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Maximum number of domains per edge application | 10 instances | 50 instances | 200 instances | Customizable |
```suggestion
| Maximum number of domains per edge application | 10 instances | 50 instances | 200 instances | Customizable |

### Secure

#### Edge Firewall

[Edge Firewall](/en/documentation/products/edge-firewall/) product, modules, and features usage **quotas** per account, according to each service plan:

| Scope | Quota for Developer Plan | Quota for Business Plan | Quota for Enterprise Plan | Quota for Mission Critical Plan |
| ---- | ---- | ---- | ---- | ---- |
| Maximum number of edge firewalls | 10 instances | 50 instances | 200 instances | Customizable |
| Maximum number of domains per edge firewall | All | All | All | All |

```

2023-11-07 14:16 UTC, Leticia-JRosa requested changes

2023-11-07 14:43 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Maximum number of domains per edge firewall | All | All | All | All |
```suggestion
```

2023-11-07 14:51 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Caching](/en/documentation/products/edge-application/edge-caching/) | Minimum TTL (default) | 60 seconds |
```suggestion
| [Edge Caching](/en/documentation/products/edge-application/edge-caching/) | Minimum TTL (default) | 60 seconds |
| [Jamstack Build](/) | Deploy hook triggers per hour | 2 |
| [Jamstack Build](/) | Deployments per hour | 2 |
```

2023-11-07 15:44 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| DDoS Protection | Bandwidth traffic | Unmetered |
```suggestion
| DDoS Protection | Bandwidth traffic | Unmetered |
| Edge Firewall | Network Lists entries | 20 thousand lines |
| Edge Firewall | ASN in a Network List | 20 thousand lines |
| Edge Firewall | IP/CIDR in a Network List | 20 thousand lines |
| Edge Firewall | Web Application Firewall | 128kb |
| Web Application Firewall | Debug Rules logs | 1500 logs |
| Web Application Firewall | WAF Tuning consult queries | 3 days |
```

2023-11-07 18:06 UTC, Leticia-JRosa requested changes

2023-11-07 18:06 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Purge (wildcard)](/en/documentation/products/edge-application/real-time-purge/) | Operations per month | 1000 operations per month |
```suggestion
| [Real-Time Purge (wildcard)](/en/documentation/products/edge-application/real-time-purge/) | Operations per day (24h interval) | Up to 2000 requests |
| [Real-Time Purge (wildcard)](/en/documentation/products/edge-application/real-time-purge/) | Wildcard URL per request | 1 |
| [Real-Time Purge (wildcard)](/en/documentation/products/edge-application/real-time-purge/) | Size per Wildcard URL  | 256 characters |
```

2023-11-07 18:06 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Maximum number of domains per edge application | 10 instances | 50 instances | 200 instances | Customizable |
```suggestion
| Maximum number of domains per edge application | 10 instances | 50 instances | 200 instances | Customizable |
| Maximum purge operations per month | The first 1000 purge operations each month are included for all customers. When exceeding this volume, user will pay for each 1000 additional purges. |
```

2023-11-07 18:26 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Application](/en/documentation/products/edge-application/) | Maximum Debug Rules logs | 1500 bytes |
```suggestion
| [Edge Application](/en/documentation/products/edge-application/) | Maximum Debug Rules logs | 1,500 bytes |
```

2023-11-07 18:44 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Code Limit (UI) | 5-6MB |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Arguments  | 100 kb |
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Code Limit (API) | 200 MB |
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Code Limit (UI) | 5-6 MB |
```

2023-11-07 18:44 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Environment variable size | 32kb |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Environment variable size | 32 kb |
```

2023-11-07 18:44 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Maximum number of versions per EdgeWorker ID | 1000 |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Maximum number of versions per EdgeWorker ID | 1,000 |
```

2023-11-07 18:44 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Memory per Isolate | 512MB |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Memory per Isolate | 512 MB |
```

2023-11-07 18:45 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Compressed size for a code bundle | 512KB |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Compressed size for a code bundle | 512 KB |
```

2023-11-07 18:45 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Disk Size | 13GB |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Deployments Created from CLI per Week | 2,000 |
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Disk Size | 13 GB |
```

2023-11-07 18:45 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Max hostnames | 5000 |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Max hostnames | 5,000 |
```

2023-11-07 18:46 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Maximum response header size for HTTP sub-requests | 8000 bytes |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Maximum response header size for HTTP sub-requests | 8,000 bytes |
```

2023-11-07 18:46 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Maximum streaming request body size when `request.body` is called in the `responseProvider` event handler | 1MB |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Maximum streaming request body size when `request.body` is called in the `responseProvider` event handler | 1 MB |
```

2023-11-07 18:46 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Uncompressed size for a code bundle | 1MB |
```suggestion
| [Edge Functions](/en/documentation/products/edge-application/edge-functions/) | Uncompressed size for a code bundle | 1 MB |
```

2023-11-07 18:46 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [L2 Caching](/en/documentation/products/edge-application/l2-caching/) | Content caching | TTL equal or greater than 2592000 seconds (30 days) |
```suggestion
| [L2 Caching](/en/documentation/products/edge-application/l2-caching/) | Content caching | TTL equal or greater than 2,592,000 seconds (30 days) |
```

2023-11-07 18:47 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Purge (History)](/en/documentation/products/edge-application/real-time-purge/) | Maximum number of wildcards URLs from which the Purge was requested | Limited to 6 months and up to 10000
```suggestion
| [Real-Time Purge (History)](/en/documentation/products/edge-application/real-time-purge/) | Maximum number of wildcards URLs from which the Purge was requested | Limited to 6 months and up to 1,000,000 requests |
```

2023-11-07 18:58 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Purge (URL and Cache Key)](/en/documentation/products/edge-application/real-time-purge/) | Size per URL or Cache Key | 4096 characters |
```suggestion
| [Real-Time Purge (URL and Cache Key)](/en/documentation/products/edge-application/real-time-purge/) | Size per URL or Cache Key | 4,096 characters |
```

2023-11-07 18:58 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Purge (wildcard)](/en/documentation/products/edge-application/real-time-purge/) | Size per Wildcard URL  | 256 characters |
```suggestion
| [Real-Time Purge (wildcard)](/en/documentation/products/edge-application/real-time-purge/) | Size per Wildcard URL | 256 characters |
```

2023-11-07 18:59 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Slice Caching Size](/en/documentation/products/edge-application/cache-settings/#slice-settings) | Slice Caching Size | 1024 kb |
```suggestion
| [Slice Caching Size](/en/documentation/products/edge-application/cache-settings/#slice-settings) | Slice Caching Size | 1,024 kb | 
```

2023-11-07 18:59 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Edge Firewall | Web Application Firewall | 128kb |
```suggestion
| Edge Firewall | Web Application Firewall | 128 kb |
```

2023-11-07 18:59 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Data Streaming](/en/documentation/products/data-streaming/) | Dispatch | 60 seconds or blocks of 2000 requests, whichever happens first. For the AWS Kinesis Data Firehose endpoint: 60 seconds or b
```suggestion
| [Data Streaming](/en/documentation/products/data-streaming/) | Dispatch | 60 seconds or blocks of 2,000 requests, whichever happens first. For the AWS Kinesis Data Firehose endpoint: 60 seconds or blocks of 500 requests |
```

2023-11-07 18:59 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Data Streaming](/en/documentation/products/data-streaming/) | UI access | Users with more than 3000 domains must use the API to edit streams |
```suggestion
| [Data Streaming](/en/documentation/products/data-streaming/) | UI access | Users with more than 3,000 domains must use the API to edit streams |
```

2023-11-07 18:59 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Events](/en/documentation/products/graphql-api-overview/) | GraphQL data transferred | 10000 lines |
```suggestion
| [Real-Time Events](/en/documentation/products/graphql-api-overview/) | GraphQL data transferred | 10,000 lines |
```

2023-11-07 19:00 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Metrics](/en/documentation/products/graphql-api-overview/) | GraphQL data transferred | 10000 lines |
```suggestion
| [Real-Time Metrics](/en/documentation/products/graphql-api-overview/) | GraphQL data transferred | 10,000 lines |
```

2023-11-07 19:06 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Real-Time Metrics](/en/documentation/products/graphql-api-overview/) | GraphQL maximum fields | 35 fields |
fui eu que tinha colocado hahaha acabei de validar com ele e é pra manter!

2023-11-07 20:28 UTC, Leticia-JRosa approved these changes
Approved!!! :D

2023-11-08 12:45 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| DDoS Protection | Bandwidth traffic | Unmetered |
```suggestion
| [DDoS Protection](/en/documentation/products/edge-firewall/ddos-protection/) | Bandwidth traffic | Unmetered |
```

2023-11-08 12:47 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Web Application Firewall | WAF Tuning consult queries | 3 days |
```suggestion
| [Edge Firewall](/en/documentation/products/edge-firewall/) | Network Lists entries | 20,000 lines |
| [Edge Firewall](/en/documentation/products/edge-firewall/) | ASN in a Network List | 20,000 lines |
| [Edge Firewall](/en/documentation/products/edge-firewall/) | IP/CIDR in a Network List | 20,000 lines |
| [Edge Firewall](/en/documentation/products/edge-firewall/) | Web Application Firewall | 128 kb |
| [Web Application Firewall](/en/documentation/products/edge-firewall/web-application-firewall/) | Maximum Debug Rules logs | 1,500 bytes |
| [Web Application Firewall](/en/documentation/products/edge-firewall/web-application-firewall/) | WAF Tuning consult queries | 3 days |
```

2023-11-08 14:54 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Platform | Keep-alive connection | Up to 15 minutes |
```suggestion
| [Platform](/en/documentation/products/edge-application/#limits) | Keep-alive connection | Up to 15 minutes |
```

2023-11-08 14:59 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +* The first 1000 purge operations per each month are included for all customers. After exceeding this volume, users will pay for each 1,000 additional purges.
```suggestion
*\ The first 1000 purge operations per each month are included for all customers. After exceeding this volume, users will pay for each 1,000 additional purges.
```

2023-11-08 15:09 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Platform | Object in cache | Maximum 10 GB per object |
```suggestion
| [Platform](/en/documentation/agreements/tos/#1-products-and-services) | Object in cache | Maximum 10 GB per object |
```

2023-11-09 12:47 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| Scope | Quota for Developer Plan | Quota for Business Plan | Quota for Enterprise Plan | Quota for Mission Critical Plan |
```suggestion
| Scope | Developer | Busines | Enterprise | Mission Critical |
```

2023-11-09 12:50 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +[Edge Application](/en/documentation/products/edge-application/) product, modules, and features usage **quotas** per account, according to each service plan:
```suggestion
[Edge Application](/en/documentation/products/edge-application/) product, modules, and features usage **quotas** per account, according to each [service plan](https://www.azion.com/en/pricing/):
```

2023-11-09 13:12 UTC, hannah-sk commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +| [Data Streaming](/en/documentation/products/data-streaming/) | Dispatch | 60 seconds or blocks of 2,000 requests, whichever happens first. For the AWS Kinesis Data Firehose endpoint: 60 seconds or
```suggestion
| [Data Streaming](/en/documentation/products/data-streaming/) | Dispatch | 60 seconds or packages of 2,000 requests, whichever happens first. For the AWS Kinesis Data Firehose endpoint: 60 seconds or packages of 500 requests |
```

2023-11-16 13:46 UTC, Leticia-JRosa requested changes
Incluída a informação de quotas na tip, e sugeri mover ela para cima, antes da descrição de limites e quotas.

2023-11-16 13:46 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +
:::tip
```suggestion
All Azion limits and quotas are customizable. If you need to increase the standard availability, contact the [sales team](https://www.azion.com/en/contact-sales/).
```
:::

2023-11-16 13:46 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +:::tip
```suggestion

```

2023-11-16 13:46 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +All Azion limits are customizable. If you need to increase the standard availability, contact the [sales team](https://www.azion.com/en/contact-sales/).
```suggestion

```

2023-11-16 13:46 UTC, Leticia-JRosa commented on src/content/docs/en/pages/main-menu/reference/limits/limits.mdx
> +:::
```suggestion

```

2023-12-13 12:00 UTC, closed without merging