[EDU-2643] cli edge app
aziontech/docs pull request #394
Opened 2023-10-31 20:10 UTC by gabriel-azion

For example:
- Add edge application CRUDL via CLI

2023-10-31 21:31 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--cdn-cache-settings-maximum-ttl` option defines the maximum time to live (TTL) of cached resources in the CDN. It sets a time limit for how long resources can be cached on the CDN servers.
```suggestion
The `--cdn-cache-settings-maximum-ttl` option defines the maximum time to live (TTL) of cached resources in the edge. It sets a time limit for how long resources can be cached on the edge nodes.
```

2023-10-31 21:36 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--host-header` option allows customization of host headers.
```suggestion
The `--host-header` option allows customization of the `Host` header.
```

2023-10-31 21:36 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--https-port` flag specifies the edge application's HTTPS Port. The default is `443`.
```suggestion
The `--https-port` flag specifies the edge application's HTTPS delivery port. The default is `443`.
```

2023-10-31 21:37 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--http-port` flag specifies the edge application's HTTP Port. The default is `80`.
```suggestion
The `--http-port` flag specifies the edge application's HTTP delivery port. The default is `80`.
```

2023-10-31 21:37 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--http-port` flag specifies the edge application's HTTP Port. The default is `80`.
Só pra separar do origin address port

2023-10-31 21:39 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--http3` option enables HTTP3.
```suggestion
The `--http3` option enables delivery in HTTP/3.
```

2023-10-31 21:56 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--application-acceleration` flag specifies whether the edge application has Application Acceleration active or not.
```suggestion
The `--application-acceleration` flag specifies whether the edge application has the [Application Acceleration](/en/documentation/products/edge-application/application-acceleration/) module active.
```

2023-10-31 21:57 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--delivery-protocol` flag specifies the edge application's Delivery Protocol.
```suggestion
The `--delivery-protocol` flag specifies the edge application's [delivery protocol](/en/documentation/products/edge-application/main-settings/).
```

2023-10-31 21:58 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--edge-functions` flag specifies whether the edge application has Edge Functions active or not.
```suggestion
The `--edge-functions` flag specifies whether the edge application has the [Edge Functions](/en/documentation/products/edge-application/edge-functions/) module active.
```

2023-10-31 21:58 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--image-optimization` flag specifies whether the edge application has Image Optimization active or not.
```suggestion
The `--image-optimization` flag specifies whether the edge application has the [Image Processor](/en/documentation/products/edge-application/image-processor/) module active.
```

2023-10-31 21:59 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--l2-caching` flag specifies whether the edge application has L2 Caching active or not.
```suggestion
The `--l2-caching` flag specifies whether the edge application has the [L2 Caching](/en/documentation/products/edge-application/l2-caching/) module active.
```

2023-10-31 22:00 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--load-balancer` flag specifies whether the edge application has Load Balancer active or not.
```suggestion
The `--load-balancer` flag specifies whether the edge application has the [Load Balancer](/en/documentation/products/edge-application/load-balancer/) module active.
```

2023-10-31 22:07 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--min-tsl-ver` flag specifies the edge application's Minimum Tls Version.
```suggestion
The `--min-tsl-ver` flag specifies the edge application's Minimum TLS Version.
```

2023-10-31 22:08 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +:::note Replace `<application_id>` in the `--application-id` flag with the actual ID of the Edge Application you want to describe.
```suggestion
:::note
Replace `<application_id>` in the `--application-id` flag with the actual ID of the Edge Application you want to describe.
```

2023-11-01 10:51 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--http-port` flag specifies the edge application's HTTP Port. The default is `80`.
```suggestion
The `--http-port` flag specifies the edge application's HTTP Port. By default, it's `80`.
```

2023-11-01 10:51 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--https-port` flag specifies the edge application's HTTPS Port. The default is `443`.
```suggestion
The `--https-port` flag specifies the edge application's HTTPS Port. By default, it's `443`.
```

2023-11-01 10:52 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--in` flag specifies the given path and JSON file to automatically update the edge application attributes; you can use `-` for reading from stdin.
```suggestion
The `--in` flag specifies the given path and JSON file to automatically update the edge application attributes. You can use `-` for reading from stdin.
```

2023-11-01 10:53 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--raw-logs` flag specifies whether the edge application has Raw Logs active or not.
o que seriam os raw logs pra estar em maiúsculo?

2023-11-01 10:53 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--application-id` flag specifies the unique identifier of the Edge Application to display its attributes in detail.
```suggestion
The `--application-id` flag specifies the unique identifier of the edge application to display its attributes in detail.
```

2023-11-01 10:53 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--id` flag specifies the unique identifier of the Edge Application.
```suggestion
The `--id` flag specifies the unique identifier of the edge application.
```

2023-11-01 10:54 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +## Global Options
```suggestion
## Global options
```

2023-11-01 10:55 UTC, hannah-sk commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +- `-y, --yes`: Answers all yes/no interactions automatically with yes.
```suggestion
- `-c, --config string`: sets the Azion configuration folder for the current command only, without changing persistent settings.
- `-d, --debug`: displays logs at a debug level.
- `-l, --log-level string`: displays logs' levels to debug (default "info").
- `-s, --silent`: silences logs completely; mostly used for automation purposes.
- `-t, --token string`: saves a given personal token locally to authorize CLI commands.
- `-y, --yes`: answers all yes/no interactions automatically with `yes`.
```

2023-11-01 10:55 UTC, hannah-sk reviewed
algumas correções de estilo, sugestões e uma dúvida

2023-11-01 11:16 UTC, bru-andrade requested changes
🤓

2023-11-01 11:45 UTC, MarianaAguilera reviewed
Agree with Hannah and Bru's comments.

2023-11-01 12:22 UTC, gabriel-azion commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--raw-logs` flag specifies whether the edge application has Raw Logs active or not.
```suggestion
The `--raw-logs` flag specifies whether the edge application has raw logs active or not.
```

2023-11-01 12:42 UTC, gabriel-azion commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +See the command and subcommands that enable the management of your Cache Settings used on the Azion Platform using **Azion CLI**.
```suggestion
See the command and subcommands that enable the management of your edge applications on the Azion Platform using **Azion**.
```

2023-11-01 18:03 UTC, gabriel-azion commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +### Required flags
```suggestion
### Required flags abbab
```

2023-11-01 19:46 UTC, hannah-sk approved these changes
um ponto: primeiras letras depois de dois pontos são minúsculas
fora isso, tudo ok!

2023-11-01 19:50 UTC, MarianaAguilera approved these changes

2023-11-08 13:49 UTC, robsongajunior approved these changes
menu lgtm

2023-11-08 14:36 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--address` option specifies the address of a resource or server.
```suggestion
The `--address` option specifies the address of the origin server.
```

2023-11-08 14:36 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--browser-cache-settings-maximum-ttl` option defines the maximum time to live (TTL) of cached resources in the browser. It sets a time limit for how long resources can be cached in the browser.
```suggestion
The `--browser-cache-settings-maximum-ttl` option defines the maximum time to live (TTL) of cached resources in the browser. It sets a time limit for how long resources can be cached in the browser, in seconds.
```

2023-11-08 14:36 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--cdn-cache-settings-maximum-ttl` option defines the maximum time to live (TTL) of cached resources in the edge. It sets a time limit for how long resources can be cached on the edge nodes.
```suggestion
The `--cdn-cache-settings-maximum-ttl` option defines the maximum time to live (TTL) of cached resources in the edge. It sets a time limit for how long resources can be cached on the edge nodes, in seconds.
```

2023-11-08 14:40 UTC, bru-andrade commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--supported-ciphers` option determines which cryptographic algorithms will be used in the TLS connections of your edge application.
```suggestion
The `--supported-ciphers` option determines which cipher suite will be used in the TLS connections of your edge application.
```

2023-11-08 14:47 UTC, bru-andrade approved these changes
Agora sim! Vou passar os mesmos comentários pro PT #404

2023-11-08 14:49 UTC, gabriel-azion commented on src/content/docs/en/pages/devtools/cli/azion-cli-alpha/edge-application/edge-application.mdx
> +The `--websocket` option allows you to establish the WebSocket communication protocol between your origin and your users under the reverse proxy architecture.
Eu vou subir e jogar essa questão pro time, ai dependendo, eu já removo

2023-11-08 14:51 UTC, merged