[EDU-3187] feat: add load balance a dns
aziontech/docs pull request #645
Opened 2024-01-12 12:32 UTC by hannah-sk

### Related issue: [EDU-3187]

### Changes

* Fixed title of the Activate DNSSEC guide.
* Added new page on how to perform a DNS load balance.

2024-01-12 12:33 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +11. Repeat steps 4 to 10 as many times as you want, but changing the **Weight** field.
```suggestion
11. Repeat steps 4 to 10 as many times as you want, but changing the **Value** and **Weight** fields.
```

2024-01-12 12:34 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +5. Repeat the steps as many times as you want, but changing the **Weight** parameter.
```suggestion
5. Repeat the steps as many times as you want, but changing the **answers_list** and **weight** parameters.
```

2024-01-12 14:17 UTC, arturdj requested changes

2024-01-12 14:47 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +    - Optionally, you can choose different values for the **Name** and **Description** fields.
```suggestion
11. Repeat steps 4 to 10 to create the other balanced DNS records needed while observing Intelligent DNS limits, and always using the same **Name** and setting the desired addresses in **Value** and weights for each record in **Weight**.
```

2024-01-12 14:48 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +    "entry": "load balance dns record",
```suggestion
    "entry": "lbexample",
```

2024-01-12 14:49 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +    "weight": 50
```suggestion
    "weight": 50,
```

2024-01-12 14:50 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +    - Optionally, you can choose different values for the **Name** and **Description** parameters.
```suggestion
```

2024-01-12 14:51 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +5. Repeat the steps as many times as you want, but changing the **answers_list** and **weight** parameters.
```suggestion
5. Repeat the steps to create the other balanced DNS records needed while observing Intelligent DNS limits, and always using the same **entry** and setting the desired addresses in the **answers_list** parameter and weights for each record in the **weight** parameter.
```

2024-01-12 14:52 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +5. In **Name**, provide the new record's name. Example: `load balance dns record`.
```suggestion
5. In **Name**, provide the new record's name. Example: `lbexample`.
```

2024-01-15 11:31 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +:::
```suggestion
:::

---

## Testing your balanced record

After configuring your balanced record, you can test and see if it's working via terminal commands:

1. Run `dig +short [your balanced hostname]` a couple of times in a row.
- You'll see the address list vary based on the record selected by the Intelligent DNS load balancer each time.
2. The response will be similar to:

```bash
dig +short lbexample @ns1.aziondns.net
192.111.0.1
```

```bash
dig +short lbexample @ns1.aziondns.net
192.111.0.2
```

```bash
dig +short lbexample @ns1.aziondns.net
192.111.0.1
```
```

2024-01-16 14:08 UTC, arturdj approved these changes

2024-01-16 14:40 UTC, gabriel-azion commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +You can use a [Intelligent DNS zone](/en/documentation/products/secure/intelligent-dns/) to create more than one record and perform a DNS load balance. Assigning different weights to each record for
```suggestion
You can use a [Intelligent DNS zone](/en/documentation/products/secure/intelligent-dns/) to create multiple records and perform a DNS load balance. Assigning different weights to each record for the same zone helps distribute incoming network traffic, ensuring optimal resource utilization and preventing overload on a single server.
```

2024-01-16 14:42 UTC, gabriel-azion commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +11. Repeat steps 4 to 10 to create the other balanced DNS records needed while observing Intelligent DNS limits, and always using the same **Name** and setting the desired addresses in **Value** and
```suggestion
11. Repeat steps 4 to 10 to create the other balanced DNS records needed while observing Intelligent DNS limits, always using the same **Name** and setting the desired addresses in **Value** and weights for each record in **Weight**.
```

2024-01-16 14:42 UTC, gabriel-azion approved these changes
some suggestions. Feel free to accept or not... LGTM

2024-01-16 15:09 UTC, MarianaAguilera commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +You can use a [Intelligent DNS zone](/en/documentation/products/secure/intelligent-dns/) to create more than one record and perform a DNS load balance. Assigning different weights to each record for
```suggestion
You can use an [Intelligent DNS zone](/en/documentation/products/secure/intelligent-dns/) to create more than one record and perform a DNS load balance. Assigning different weights to each record for a same zone helps distribute incoming network traffic, ensuring optimal resource utilization and preventing overload on a single server.
```

2024-01-16 15:16 UTC, MarianaAguilera approved these changes

2024-01-17 13:43 UTC, bru-andrade commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +5. Repeat the steps to create the other balanced DNS records needed while observing Intelligent DNS limits, and always using the same **entry** and setting the desired addresses in the **answers_list
```suggestion
5. Repeat the steps to create the other balanced DNS records needed while observing Intelligent DNS limits, always using the same `entry` and setting the desired addresses in the `answers_list` parameter and weights for each record in the `weight` parameter.
```

2024-01-17 13:48 UTC, bru-andrade approved these changes

2024-01-18 14:50 UTC, hannah-sk commented on src/content/docs/en/pages/secure-journey/intelligent-dns-advanced-configurations/load-balance-dns.mdx
> +2. You'll receive a response with all your existing edge firewalls. Copy the value of the `<id>` that you want to use.
```suggestion
2. You'll receive a response with all your existing zones. Copy the value of the `<id>` that you want to use.
```

2024-01-19 11:22 UTC, merged