[EDU-3105] feat: authors component shows commit history for file
aziontech/docs pull request #655
Opened 2024-01-16 18:20 UTC by bru-andrade

### Related issue: [EDU-3105]

### Changes

Repurposed ContributorList into AuthorList to show contributing authors pulled from commit history

Goal: test in stage and production envs

### Additional links

2024-01-16 21:03 UTC, lfsigreja requested changes

2024-01-16 21:03 UTC, lfsigreja commented on src/components/AuthorList.astro
> +		height: var(--avatar-size);
O custom style do docs trás o <img /> com apenas 70% de max-width (por conta das imagens dentro do mdx), esse componente precisa ser 100% (era para ser assim no anterior, devemos ter esquecido de aplicar lá quando mudamos)

Coloca max-width: 100% e de uma olhada como fica, acredito que seja muito melhor.

2024-01-16 21:09 UTC, bru-andrade commented on src/components/AuthorList.astro
> +				src={`https://avatars.githubusercontent.com/u/${item.id}?s=64`}
```suggestion
				src={`https://avatars.githubusercontent.com/u/${item.id}?s=32`}
```

2024-01-16 21:10 UTC, bru-andrade commented on src/components/AuthorList.astro
> +		width: var(--avatar-size);
```suggestion
		max-width: 100%;
```

2024-01-16 22:48 UTC, lfsigreja approved these changes
LGTM

2024-01-17 12:04 UTC, gabriel-azion approved these changes

2024-01-18 13:23 UTC, robsongajunior approved these changes
LGTM

2024-01-18 13:23 UTC, merged