EDU-1933-rules-engine
aziontech/docs pull request #79
Opened 2023-08-07 16:08 UTC by bru-andrade

Nova rules engine!

2023-08-07 16:35 UTC, gabriel-azion requested changes
some typos

2023-08-10 13:43 UTC, hannah-sk approved these changes
deixei mais algumas sugestões.
dá pra mudar já os componentes de caution etc!

2023-08-11 18:40 UTC, MarianaAguilera approved these changes

2023-08-14 12:55 UTC, gabriel-azion approved these changes

2023-08-14 13:14 UTC, ghost approved these changes

2023-08-14 17:04 UTC, merged