feat: ajustes nomes de produtos
aziontech/docs pull request #803
Opened 2024-03-01 19:27 UTC by Vitor-Azion

- [PMK-5791] feat: adding new names for products (tiered cache, edge cache, edge dns, data stream)

### Changes

Mudança nos nomes dos produtos.

2024-03-04 11:26 UTC, hannah-sk commented on src/content/docs/en/pages/agreements/tos/21-february-2024/21-february-2024.mdx
> +namespace: documentation_agreements_service_terms
```suggestion
namespace: documentation_agreements_service_terms_21_february_2024
```

2024-03-04 11:26 UTC, hannah-sk commented on src/content/docs/en/pages/agreements/tos/21-february-2024/21-february-2024.mdx
> +permalink: /documentation/agreements/tos/
```suggestion
permalink: /documentation/agreements/tos/21-february-2024/
```

2024-03-04 11:30 UTC, hannah-sk commented on src/content/docs/pt-br/pages/contratos/tos/21-february-2024/21-february-2024.mdx
> +permalink: /documentacao/contratos/tds/
```suggestion
namespace: documentation_agreements_service_terms_21_february_2024
permalink: /documentacao/contratos/tds/21-fevereiro-2024/
```

2024-03-04 11:32 UTC, hannah-sk commented on src/content/docs/pt-br/pages/contratos/tos/index.mdx
>  **Edge Storage**: projetado como um serviço para o armazenamento eficiente, seguro e escalável de objetos, organizados em buckets que podem ser públicos ou privados. Cada objeto é composto por um ide
```suggestion
**Edge Storage**: projetado como um serviço para o armazenamento eficiente, seguro e escalável de objetos, organizados em buckets que podem ser públicos ou privados. Cada objeto é composto por um identificador único, seus dados e metadados. Inclui capacidades essenciais, como escrita e acesso aos buckets e objetos por meio de API REST ou protocolo S3. A distribuição dos objetos armazenados no Edge Storage para o usuário final deve ser realizada por meio de uma Edge Application, podendo gerar tarifação conforme as métricas correspondentes. O acesso direto aos objetos armazenados no Edge Storage, sem passar por uma Edge Application, estará sujeito a limitações de taxa de acesso. Ao utilizar os serviços de armazenamento oferecidos pela Azion, o cliente reconhece e concorda que é integralmente responsável pelo conteúdo que escolhe fazer upload, armazenar ou compartilhar por meio de nossa plataforma. Isso inclui assumir todos os riscos relacionados à propriedade, legalidade e uso adequado desses materiais, garantindo possuir todos os direitos, licenças, consentimentos e permissões necessários para tal. Adicionalmente, o cliente entende que a Azion não assume nenhuma responsabilidade pelo conteúdo armazenado em seus sistemas, estando isenta de qualquer reivindicação relacionada à violação de direitos autorais, marca registrada ou qualquer outro direito de propriedade intelectual de terceiros, bem como de qualquer responsabilidade legal decorrente do conteúdo fornecido pelo usuário. É dever do cliente assegurar que seu conteúdo esteja em conformidade com todas as leis e regulamentos aplicáveis. A Azion fará todos os esforços comercialmente razoáveis para garantir a disponibilidade e a durabilidade dos objetos do cliente armazenados em nossa infraestrutura, porém não existem garantias contra a perda de dados. Enquanto proporcionamos a plataforma e as ferramentas necessárias para o armazenamento, a proteção contra perda de dados é dever do cliente, que deve adotar medidas proativas para garantir a segurança de seus dados críticos, tais como backup e/ou snapshot. Salvo disposição em contrário no Contrato do Cliente ou quaisquer documentos anexos a ele, a cobrança do Edge Storage será realizada por (a) Storage; (b) Class A Operations; e (c) Class B Operations, de acordo com os volumes consumidos.
```

2024-03-04 11:34 UTC, hannah-sk requested changes
@Vitor-Azion left comments to update namespace and permalink for versioning files

2024-03-07 19:57 UTC, hannah-sk approved these changes

2024-03-07 20:04 UTC, gabriel-azion approved these changes

2024-03-15 18:04 UTC, merged