EDU-2070-digital-certificates
aziontech/docs pull request #86
Opened 2023-08-08 13:09 UTC by bru-andrade

Digital certificates template

2023-08-08 14:01 UTC, hannah-sk requested changes
algumas questões de estilo + sugestões ✌️

2023-08-09 16:37 UTC, gabriel-azion approved these changes

2023-08-09 18:32 UTC, mariiaguirre approved these changes

2023-08-10 13:28 UTC, hannah-sk approved these changes

2023-08-10 14:54 UTC, merged