[EDU-4179]
aziontech/docs pull request #969
Opened 2024-05-21 17:34 UTC by MarianaAguilera

### Related issue:

[EDU-4179]

### Changes

- Add Security Modernization architecture file (PT and EN).
- Add cards in Architectures home (PT and EN).

### Additional links

n/a.

2024-05-21 17:49 UTC, gabriel-azion commented on src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
> +1. Crie um edge application usando uma das opções recomendadas:
```suggestion
1. Crie uma edge application usando uma das opções recomendadas:
```

2024-05-21 17:50 UTC, gabriel-azion commented on src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
> +4. Se a requisição não corresponder a uma regra e não for bloqueada, o conteúdo continua o fluxo de requisição para o Edge Application.
```suggestion
4. Se a requisição não corresponder a uma regra e não for bloqueada, o conteúdo continua o fluxo de requisição para a Edge Application.
```

2024-05-21 17:50 UTC, gabriel-azion commented on src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
> +- O Edge Application usa o Rules Engine para identificar se há regras relacionadas ao armazenamento em cache, otimização de imagem, cookies e redirecionamentos, entre outros.
```suggestion
- A Edge Application usa o Rules Engine para identificar se há regras relacionadas ao armazenamento em cache, otimização de imagem, cookies e redirecionamentos, entre outros.
```

2024-05-21 19:46 UTC, arturdj requested changes

2024-05-21 19:46 UTC, arturdj commented on src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
> +- Enable the DDoS Protection Unmetered, Web Application Firewall, Network Layer Protection, and Edge Functions modules.
DDoS é ativado por padrão. Não pode ser "ativado".

2024-05-21 19:46 UTC, arturdj commented on src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
> +6. [Create rules in Rules Engine](/en/documentation/products/guides/secure/work-with-rules-engine/) for Edge Firewall.
Acho que podemos explorar melhor que a regra vai definir os critérios e como usar os componentes cadastrados nos itens acima. Só citar genericamente basta.

2024-05-21 19:46 UTC, arturdj commented on public/assets/docs/images/uploads/diagram-security-modernization.png
A caixa "DDoS Protection" vem antes do handshake de segurança (à esquerda). MOTIVO: handshake ocorre no layer 7 e nosso DDOS é antes, na 3 e 4.

útil colocar uma legenda no ícone do hanshake também.

2024-05-21 19:54 UTC, MarianaAguilera commented on src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
> +- Enable the DDoS Protection Unmetered, Web Application Firewall, Network Layer Protection, and Edge Functions modules.
```suggestion
- Enable the Web Application Firewall, Network Layer Protection, and Edge Functions modules.
```

2024-05-21 19:55 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
> +- Habilite os módulos DDoS Protection Unmetered, Web Application Firewall, Network Layer Protection e Edge Functions.
```suggestion
- Habilite os módulos Web Application Firewall, Network Layer Protection e Edge Functions.
```

2024-05-21 20:10 UTC, MarianaAguilera commented on src/content/docs/en/pages/architectures/security-modernization/security-modernization-with-edge-computing.mdx
> +6. [Create rules in Rules Engine](/en/documentation/products/guides/secure/work-with-rules-engine/) for Edge Firewall.
```suggestion
6. [Create rules in Rules Engine](/en/documentation/products/guides/secure/work-with-rules-engine/) for Edge Firewall to define the behavior to be executed when the Edge Firewall detects a request matching the criteria defined by the rule sets, network lists, and edge functions.
```

2024-05-21 20:11 UTC, MarianaAguilera commented on src/content/docs/pt-br/pages/arquiteturas/security-modernization/security-modernization-com-edge-computing.mdx
> +6. [Crie regras no Rules Engine](/pt-br/documentacao/produtos/guias/secure/trabalhar-com-rules-engine/) para o Edge Firewall.
```suggestion
6. [Crie regras no Rules Engine](/pt-br/documentacao/produtos/guias/secure/trabalhar-com-rules-engine/) do Edge Firewall para definir o comportamento a ser executado quando o Edge Firewall detectar uma requisição que corresponda aos critérios definidos pelos rule sets, network lists e edge functions.
```

2024-05-22 12:38 UTC, mrmessa commented on public/assets/docs/images/uploads/diagram-security-modernization.png
Artur, vamos conversar pois tomo como exemplo de camada 7 mitigados o slowloris, http flood, HTTP GET/POST flood, Cache-bypass attacks, Resource exhaustion attacks). Isso não muda a possibilidade de ajuste.

2024-05-22 13:22 UTC, arturdj commented on public/assets/docs/images/uploads/diagram-security-modernization.png
Está correto. Temos a proteção DDoS L7 que ocorre logo depois do handshake também (para casos HTTP/S) e direto quando HTTP não seguro.

2024-05-23 13:28 UTC, arturdj approved these changes

2024-05-23 17:02 UTC, merged